# Database configuration
Database:
  DataSource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/certauthority?verifyServerCertificate=false&useSSL=true
    user: causer
    password: causer
    properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.generate_statistics: true
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true  
    maxWaitForConnection: 1s
    validationQuery: "SELECT 1"
    minSize: 2
    maxSize: 10
    checkConnectionWhileIdle: true

# Server configuration
server:
  applicationConnectors:
  - type: http
    port: 8443
  adminConnectors:
  - type: http
    port: 9443
  requestLog:
    appenders:
      - type: file
        threshold: TRACE
        currentLogFilename: /projects/certificate-authority/ca-assembly/target/ca-1.0.0-SNAPSHOT/ca-1.0.0-SNAPSHOT/logs/requests.log
        archivedLogFilenamePattern: /projects/certificate-authority/ca-assembly/target/ca-1.0.0-SNAPSHOT/ca-1.0.0-SNAPSHOT/logs/requests-%d.log
        archive: true
        archivedFileCount: 5
        timeZone: CET

# Logging configuration
logging:
  level: TRACE
  loggers:
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
  appenders:
    - type: file
      threshold: TRACE
      currentLogFilename: /projects/certificate-authority/ca-assembly/target/ca-1.0.0-SNAPSHOT/ca-1.0.0-SNAPSHOT/logs/service.log
      archivedLogFilenamePattern: /projects/certificate-authority/ca-assembly/target/ca-1.0.0-SNAPSHOT/ca-1.0.0-SNAPSHOT/service-%d.log
      archive: true
      archivedFileCount: 5
      timeZone: CET
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{txid}] %logger{35} - %msg%n"